apiVersion: v1
kind: Service
metadata:
  labels:
    app: library-db-app
  name: library-db-service
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: library-db-app